-- Script simplificado para inserir roadmap
-- Execute TUDO de uma vez

-- Primeiro, limpar
DELETE FROM project_documentation WHERE section = 'roadmap';

-- Inserir dados
INSERT INTO project_documentation (section, content, updated_at)
SELECT 
    'roadmap',
    '[
        {"id": "roadmap-1", "title": "📧 Templates React Email", "description": "📊 Impacto: Alto | ⏱️ Tempo: 8-12h | 💰 Custo: R$ 0 (grátis)\\n\\n✅ BENEFÍCIOS:\\n• Emails 100% responsivos (mobile, desktop, tablet)\\n• Preview em tempo real durante desenvolvimento\\n• Manutenção simplificada (componentes reutilizáveis)\\n• Suporte a dark mode automático\\n• Testes A/B facilitados\\n\\n💡 ROI ESPERADO:\\n• +30% taxa de abertura (open rate)\\n• +25% taxa de clique (CTR)\\n• -50% tempo de criação de novos emails\\n• Redução de 80% em bugs de renderização", "done": false},
        {"id": "roadmap-2", "title": "🎨 Dark Mode", "description": "📊 Impacto: Médio | ⏱️ Tempo: 12-16h | 💰 Custo: R$ 0\\n\\n✅ BENEFÍCIOS:\\n• Reduz fadiga ocular em 40%\\n• Economiza bateria em dispositivos móveis\\n• Preferência de 60% dos usuários modernos\\n• Diferencial competitivo visual\\n• Melhora acessibilidade\\n\\n💡 ROI ESPERADO:\\n• +15% tempo médio de sessão\\n• +10% satisfação do usuário (NPS)\\n• Redução de 20% em reclamações de UX\\n• Aumento de 8% em retenção", "done": false},
        {"id": "roadmap-3", "title": "📊 Geolocalização", "description": "📊 Impacto: Alto | ⏱️ Tempo: 16-20h | 💰 Custo: R$ 280/mês (MaxMind GeoIP2)\\n\\n✅ BENEFÍCIOS:\\n• Mapa interativo de cliques por país/cidade\\n• Segmentação geográfica de campanhas\\n• Insights de mercados inexplorados\\n• Detecção de fraude por localização\\n• Relatórios de performance regional\\n\\n💡 ROI ESPERADO:\\n• +20% conversão de Pro para Business\\n• Justifica aumento de R$ 50/mês no plano\\n• Break-even com apenas 6 upgrades/mês\\n• Feature premium que concorrentes não têm", "done": false},
        {"id": "roadmap-4", "title": "📧 Preferências Email", "description": "📊 Impacto: Alto | ⏱️ Tempo: 6-8h | 💰 Custo: R$ 0\\n\\n✅ BENEFÍCIOS:\\n• Compliance total com LGPD/GDPR\\n• Usuários controlam frequência de emails\\n• Reduz spam reports em 90%\\n• Melhora reputação do domínio\\n• Evita multas de até R$ 50 milhões (LGPD)\\n\\n💡 ROI ESPERADO:\\n• Essencial para escalabilidade internacional\\n• Reduz unsubscribes em 40%\\n• Melhora deliverability em 25%\\n• Proteção legal obrigatória", "done": false},
        {"id": "roadmap-5", "title": "📧 Triggers Automáticos", "description": "📊 Impacto: Alto | ⏱️ Tempo: 8-10h | 💰 Custo: R$ 0 (incluído Resend)\\n\\n✅ BENEFÍCIOS:\\n• Welcome email automático ao cadastro\\n• Nurturing sem esforço manual\\n• Onboarding guiado por email\\n• Re-engajamento de inativos\\n• Upsell automatizado\\n\\n💡 ROI ESPERADO:\\n• +40% ativação de novos usuários\\n• +25% conversão free → paid\\n• Economia de 10h/semana de trabalho manual\\n• +15% LTV (Lifetime Value)", "done": false},
        {"id": "roadmap-6", "title": "📧 Relatórios Semanais", "description": "📊 Impacto: Médio | ⏱️ Tempo: 10-12h | 💰 Custo: R$ 0 (incluído Resend)\\n\\n✅ BENEFÍCIOS:\\n• Mantém usuários engajados semanalmente\\n• Mostra valor do produto constantemente\\n• Insights automáticos de performance\\n• Incentiva uso regular da plataforma\\n• Reduz esquecimento da ferramenta\\n\\n💡 ROI ESPERADO:\\n• -15% taxa de cancelamento (churn)\\n• +20% frequência de uso\\n• +10% upgrades (veem valor)\\n• Custo de retenção próximo de zero", "done": false},
        {"id": "roadmap-7", "title": "⏰ Cron Jobs", "description": "📊 Impacto: Alto | ⏱️ Tempo: 4-6h | 💰 Custo: R$ 0 (incluído Vercel)\\n\\n✅ BENEFÍCIOS:\\n• Infraestrutura para automações\\n• Envios agendados confiáveis\\n• Limpeza automática de dados\\n• Relatórios programados\\n• Escalabilidade garantida\\n\\n💡 ROI ESPERADO:\\n• Base essencial para 10+ features futuras\\n• Economia de R$ 200/mês (vs serviços externos)\\n• 99.9% confiabilidade\\n• Permite features enterprise", "done": false},
        {"id": "roadmap-8", "title": "📊 Exportar Relatórios", "description": "📊 Impacto: Médio | ⏱️ Tempo: 6-8h | 💰 Custo: R$ 0\\n\\n✅ BENEFÍCIOS:\\n• Exportação CSV/PDF/Excel\\n• Compartilhamento com equipe\\n• Análise em ferramentas externas\\n• Compliance e auditoria\\n• Apresentações para stakeholders\\n\\n💡 ROI ESPERADO:\\n• Feature esperada em 80% dos planos Business\\n• Facilita vendas B2B em 35%\\n• Reduz solicitações de suporte\\n• Diferencial em propostas comerciais", "done": false},
        {"id": "roadmap-9", "title": "💳 Integração Pagamento", "description": "📊 Impacto: CRÍTICO | ⏱️ Tempo: 24-32h | 💰 Custo: 4.99% + R$ 0,49/transação (Stripe BR)\\n\\n✅ BENEFÍCIOS:\\n• MONETIZAÇÃO REAL do produto\\n• Receita recorrente previsível (MRR)\\n• Pagamentos em cartão, Pix, boleto\\n• Gestão automática de cobranças\\n• Retry automático de falhas\\n\\n💡 ROI ESPERADO:\\n• Essencial para viabilidade do negócio\\n• Meta: R$ 10.000 MRR em 6 meses\\n• Custo de 5% vs 15% de outros gateways\\n• Prioridade ABSOLUTA #1", "done": false},
        {"id": "roadmap-10", "title": "💰 Sistema Checkout", "description": "📊 Impacto: CRÍTICO | ⏱️ Tempo: 16-20h | 💰 Custo: R$ 0 (usa Stripe)\\n\\n✅ BENEFÍCIOS:\\n• Fluxo otimizado de conversão\\n• Aplicação automática de cupons\\n• Upsell no momento da compra\\n• Checkout em 1 clique\\n• Recuperação de carrinho abandonado\\n\\n💡 ROI ESPERADO:\\n• Cada 1% de melhoria = +R$ 500-2000 MRR\\n• Taxa de conversão alvo: 15-20%\\n• Reduz abandono em 40%\\n• Essencial para crescimento", "done": false},
        {"id": "roadmap-11", "title": "🔄 Gerenciar Assinaturas", "description": "📊 Impacto: Alto | ⏱️ Tempo: 12-16h | 💰 Custo: R$ 0 (incluído Stripe)\\n\\n✅ BENEFÍCIOS:\\n• Self-service total (reduz suporte)\\n• Upgrade/downgrade sem atrito\\n• Pausa temporária de assinatura\\n• Cancelamento com feedback\\n• Histórico completo de pagamentos\\n\\n💡 ROI ESPERADO:\\n• -20% churn (facilita downgrade vs cancelar)\\n• -60% tickets de suporte\\n• +15% upgrades (processo simples)\\n• Economia de R$ 2000/mês em suporte", "done": false},
        {"id": "roadmap-12", "title": "🧾 Sistema Faturas", "description": "📊 Impacto: Médio | ⏱️ Tempo: 8-12h | 💰 Custo: R$ 0 (Stripe gera)\\n\\n✅ BENEFÍCIOS:\\n• Faturas automáticas por email\\n• Compliance fiscal brasileiro\\n• Notas fiscais integradas (futuro)\\n• Histórico para contabilidade\\n• Profissionalismo em vendas B2B\\n\\n💡 ROI ESPERADO:\\n• Obrigatório para 90% empresas\\n• Facilita vendas corporativas em 50%\\n• Reduz fricção em procurement\\n• Aumenta ticket médio B2B", "done": false},
        {"id": "roadmap-13", "title": "⏰ Links Expiráveis", "description": "📊 Impacto: Alto | ⏱️ Tempo: 8-10h | 💰 Custo: R$ 0\\n\\n✅ BENEFÍCIOS:\\n• Campanhas com prazo definido\\n• Segurança aumentada\\n• Controle de acesso temporal\\n• Senso de urgência (FOMO)\\n• Limpeza automática de links antigos\\n\\n💡 ROI ESPERADO:\\n• Feature premium diferenciadora\\n• Comum em planos Business+ (R$ 200/mês)\\n• +30% conversão em campanhas limitadas\\n• Casos de uso: eventos, promoções, beta", "done": false},
        {"id": "roadmap-14", "title": "🔒 Proteção Senha", "description": "📊 Impacto: Médio | ⏱️ Tempo: 6-8h | 💰 Custo: R$ 0\\n\\n✅ BENEFÍCIOS:\\n• Conteúdo exclusivo protegido\\n• Segurança adicional\\n• Casos de uso premium\\n• Controle de acesso granular\\n• Ideal para clientes corporativos\\n\\n💡 ROI ESPERADO:\\n• Diferencial competitivo claro\\n• Atrai clientes enterprise\\n• Casos de uso: materiais internos, beta privado\\n• Justifica plano premium", "done": false},
        {"id": "roadmap-15", "title": "📊 A/B Testing", "description": "📊 Impacto: Alto | ⏱️ Tempo: 20-24h | 💰 Custo: R$ 0 (lógica própria)\\n\\n✅ BENEFÍCIOS:\\n• Testa múltiplas versões de destino\\n• Otimização baseada em dados\\n• Insights valiosos de comportamento\\n• ROI mensurável de campanhas\\n• Decisões data-driven\\n\\n💡 ROI ESPERADO:\\n• Clientes pagam R$ 100-300/mês por isso\\n• +30% LTV com otimizações\\n• Feature que Bitly cobra caro\\n• Essencial para marketing profissional", "done": false}
    ]'::jsonb,
    NOW();

-- Verificar
SELECT 
    section,
    jsonb_array_length(content) as total,
    updated_at
FROM project_documentation
WHERE section = 'roadmap';
